eclipse/xtext-umbrella

releng/gradle-composite/.project, releng/gradle-composite/GenerateBuildshipPreferences.launch, releng/gradle-composite/build.gradle
generating buildship prefs files
=> generating buildship prefs files

releng/gradle-composite/GenerateBuildshipPreferences.launch, releng/gradle-composite/settings.gradle
=> optimized prefs generation

releng/gradle-composite/.settings/org.eclipse.buildship.core.prefs, releng/gradle-composite/build.gradle
create .settings folder if it does not exist
Signed-off-by: Christian Dietrich <christian.dietrich@advantest.de>
=> create .settings folder if it does not exist

releng/gradle-composite/build.gradle
use absolute path for composite. fixes #16
=> use absolute path for composite

releng/gradle-composite/build.gradle
generate buildship prefs only once
=> generate buildship prefs only once

releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> updated purexbase to new workflow

releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> fixed broken xtext repo regarding xtext/xbase.ui.testing

releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> fixed broken build due lsp4j changes

releng/org.eclipse.xtext.sdk.parent/pom.xml
Updated Tycho to Version 1.0.0
=> Updated Tycho to Version 1.0.0

releng/gradle-composite/build.gradle
=> use relative paths #30

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> fixed broken gson repo #34

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> use orbit release repo

releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/.project, releng/org.eclipse.xtext.docs.feature/.settings/org.eclipse.core.resources.prefs, releng/org.eclipse.xtext.docs.feature/.settings/org.eclipse.core.runtime.prefs, releng/org.eclipse.xtext.docs.feature/build.properties, releng/org.eclipse.xtext.docs.feature/feature.properties, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.license.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/pom.xml
=> moved doc and lic feature to umbrella

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
package asm 6 to update site and require it from features
https://github.com/eclipse/xtext/issues/1161
=> package asm 6 to update site and require it from features

gitAll
=> make gitAll quieter

releng/org.eclipse.xtext.sdk.parent/pom.xml
update to tycho 1.1.0 https://github.com/eclipse/xtext/issues/1172
=> update to tycho 1.1.0

adjustPipelines.sh
[#47] fixed bug in logical name calculation
=> [#47] fixed bug in logical name calculation

adjustPipelines.sh, allDirectories, gitAll
Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>
`allDirectories` was very hard to read and duplicated in `gitAll` so I put it into it's own script
=> Abstracted getAllDirectories into a separate script

adjustPipelines.sh
[#52]
made adjustPipelines.sh work with linux and mac
=> made adjustPipelines.sh work with linux and mac

adjustPipelines.sh
Reverts eclipse/xtext-umbrella#53
=> Revert "made adjustPipelines.sh work with linux and mac"

adjustPipelines.sh
=> [#52] fixed script for mac and linux

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> [533359] use signed antlr

releng/.project, releng/org.eclipse.xtext.releng.simrel.tests/.classpath, releng/org.eclipse.xtext.releng.simrel.tests/.project, releng/org.eclipse.xtext.releng.simrel.tests/.settings/org.eclipse.jdt.core.prefs, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/build.properties, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/src/org/eclipse/xtext/releng/simrel/tests/RepositoryTest.java
=> [#58] Enable simrel reports for Tycho build

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> Java 10 Integration

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> [eclipse/xtext#1198] Update Orbit URL to Photon M7

releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml
=> [eclipse/xtext#1225] Update to Tycho 1.2.0

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> updated orbit to photon release

releng/org.eclipse.xtext.sdk.p2-repository/category.xml
[#69]specified specific junit version for update site
=> [#69]specified specific junit version for update site

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1168] set minimal target to oxygen
=> [eclipse/xtext#1168] set minimal target to oxygen

releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/.project, releng/org.eclipse.xtext.xtext.ui.graph.feature/build.properties, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.properties, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>
=> [eclipse/xtext#1244] Add optional feature for graph view.

releng/org.eclipse.xtend.sdk.feature/p2.inf, releng/org.eclipse.xtext.sdk.feature/build.properties, releng/org.eclipse.xtext.sdk.feature/p2.inf
=> [#75] removed touchpoints

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1266] Update to ASM 6.2
=> [eclipse/xtext#1266] Update to ASM 6.2

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.license.feature/feature.xml, releng/org.eclipse.xtext.license.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> updated versions to 2.16.0

releng/org.eclipse.xtext.sdk.p2-repository/pom.xml
Signed-off-by: Prajwal Gowda <pgowda@itemis.de>
=> [release] version 2.16.0.M1

releng/org.eclipse.xtext.license.feature/feature.properties, releng/org.eclipse.xtext.license.feature/license.html, releng/org.eclipse.xtext.license.feature/notice.html
[#540593] updated license to latest version
=> [#540593] updated license to latest version

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1325] switch to ASM 7
=> [eclipse/xtext#1325] switch to ASM 7

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> change version 2.16.0 -> 2.17.0

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> switched to orbit 2019-03

releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml
[eclipse/xtext#1322] switched to tycho 1.3.0
=> [eclipse/xtext#1322] switched to tycho 1.3.0

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
=> bumped min mwe version

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
[eclipse/xtext#1414] prepared master for version 2.18.0 
=> [eclipse/xtext#1414] prepared master for version 2.18.0

adjustPipelines.sh, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> use https to access typefox jenkins

releng/org.eclipse.xtext.sdk.feature/feature.xml
Signed-off-by: Holger Schill <Holger.Schill@itemis.de>
=> Remove IDEA since the support has been dropped.

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> remove idea gen

releng/docker/buildenv/Dockerfile, releng/docker/buildenv/build.sh, releng/docker/buildenv/push.sh, releng/docker/buildenv/run.sh
=> [eclipse/xtext#1418] Provide Docker image for build environment

CBI.Jenkinsfile
=> [eclipse/xtext#1309] Provide Jenkinsfile for Eclipse CBI

releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml
[eclipse/xtext#1422] update to tycho 1.4.0
=> [eclipse/xtext#1422] update to tycho 1.4.0

CBI.Jenkinsfile, Jenkinsfile
[eclipse/xtext#1427] disable p2 mirrors
=> [eclipse/xtext#1427] disable p2 mirrors

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties
=> update to gradle 5.4.1

releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml
=> fixed wrong usage of http

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [eclipse/xtext#1474] Prepare Master for 2.19

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1475] build against orbit 2019-09
=> [eclipse/xtext#1475] build against orbit 2019-09

releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
Fixes eclipse/xtext#1398 and eclipse/xtext-lib#111
=> update to guava 27.1

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
=> [eclipse/xtext#1485] update to mwe 2.11

releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext-xtend#818] Add classgraph to target platform
=> [eclipse/xtext-xtend#818] Add classgraph to target platform

Jenkinsfile
=> [eclipse/xtext#1384] Convert to declarative pipeline

releng/jenkins/cleanup-project-storage/Jenkinsfile
Also-by: Karsten Thoms <karsten.thoms@itemis.de>
=> [eclipse/xtext#1471] Add releng job for cleaning up nightly

releng/jenkins/sign-and-deploy/Jenkinsfile, releng/jenkins/sign-and-deploy/scripts/create_composite_update_site.sh, releng/jenkins/sign-and-deploy/scripts/get_build_type.sh, releng/jenkins/sign-and-deploy/scripts/get_property.sh
In addition, this commit moves some duplicated scripts from Jenkinsfile to
external files
=> [eclipse/xtext#1505] Add recreation of composite update sites

releng/jenkins/sign-and-deploy/Jenkinsfile
=> [eclipse/xtext#1514] Fix minor releng issues with sign-and-deploy

CBI.Jenkinsfile, releng/jenkins/sign-and-deploy/Jenkinsfile
=> [eclipse/xtext#1515] fine-tune when slack gets notified

CBI.Jenkinsfile
[#149] removed unused target platform parameter
=> [#149] removed unused target platform parameter

CBI.Jenkinsfile, releng/jenkins/sign-and-deploy/Jenkinsfile
[eclipse/xtext#1515] Cleanup notifications
=> [eclipse/xtext#1515] Cleanup notifications

CBI.Jenkinsfile, releng/jenkins/sign-and-deploy/Jenkinsfile
=> fixed slack notifications

CBI.Jenkinsfile, Jenkinsfile
[eclipse/xtext#1503] Add master-only cron trigger
=> [eclipse/xtext#1503] Add master-only cron trigger

releng/docker/xtext-web-deploy/Jenkinsfile, releng/docker/xtext-web-deploy/xtext-web/Dockerfile
[eclipse/xtext#1533] Provide Jenkins job to build xtext-web Docker Image
=> [eclipse/xtext#1533] Provide Jenkins job to build xtext-web Docker Image

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Set version to 2.20.0

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties, releng/gradle-composite/gradlew
[eclipse/xtext#1520] update to gradle 5.6.1
=> [eclipse/xtext#1520] update to gradle 5.6.1

Jenkinsfile, releng/jenkins/cleanup-project-storage/Jenkinsfile
fixed settings.xml config in Jenkinsfile
=> fixed settings.xml config in Jenkinsfile

releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml
[eclipse/xtext#1553] update to tycho 1.5.0
=> [eclipse/xtext#1553] update to tycho 1.5.0

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1567] Upgrade to asm 7.2
=> [eclipse/xtext#1567] Upgrade to asm 7.2

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties
[eclipse/xtext#1563] update to gradle 5.6.3
=> [eclipse/xtext#1563] update to gradle 5.6.3

releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml
[eclipse/xtext#1566] update to tycho 1.5.1
=> [eclipse/xtext#1566] update to tycho 1.5.1

releng/jenkins/release-simrel-update/Jenkinsfile, releng/jenkins/sign-and-deploy/Jenkinsfile
* Add job for automatically updating the simrel repository
* Fix failing of pipeline when redeploying milestone/release
=> Add Update SimRel Job

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
[eclipse/xtext#1609] update to mwe 2.11.1
=> [eclipse/xtext#1609] update to mwe 2.11.1

Jenkinsfile
This change triggers sign-and-deploy for builds running on a milestone / release branch.
I have created for test purpose the branch milestone_2.20.0.Beta on xtext.umbrella. The job [`xtext-umbrella/job/milestone_2.20.0.Beta/1`](https://ci.eclipse.org/xtext/job/xtext-umbrella/job/milestone_2.20.0.Beta/1/) triggered [`sign-and-deploy#328`](https://ci.eclipse.org/xtext/job/releng/job/sign-and-deploy/328/rebuild/parameterized) with
- `RELEASE_TYPE=Beta`
- `BRANCH_TO_DEPLOY=milestone_2.20.0.Beta`
=> [releng] Trigger downstream job 'sign-and-deploy' for release builds

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.21.0

releng/jenkins/sign-and-deploy/Jenkinsfile
[eclipse/xtext#1596] Remove release branches after release
=> [eclipse/xtext#1596] Remove release branches after release

releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1282] update to EMF 2.20
=> [eclipse/xtext#1282] update to EMF 2.20: adapted features & target

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1605] update orbit to 2020-03
=> [eclipse/xtext#1605] update orbit to 2020-03

releng/jenkins/bot-updates/Jenkinsfile
[eclipse/xtext#1640] Fix update orbit url condition
=> [eclipse/xtext#1640] Fix update orbit url condition

releng/jenkins/bot-updates/Jenkinsfile
[releng] Add a warning about the bot user and ECA checks
=> [releng] Add a warning about the bot user and ECA checks

releng/jenkins/sign-and-deploy/Jenkinsfile
[eclipse/xtext#1596] Add sshagent to branch deletion stage
=> [eclipse/xtext#1596] Add sshagent to branch deletion stage

releng/jenkins/bot-updates/Jenkinsfile
[eclipse/xtext#1644] removed obsolete information
=> [eclipse/xtext#1644] removed obsolete information

releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml
[eclipse/xtext#1643] update to tycho 1.6.0
=> [eclipse/xtext#1643] update to tycho 1.6.0

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> use explicit junit 4.12

Contribute.md, LICENSE, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.releng.simrel.tests/src/org/eclipse/xtext/releng/simrel/tests/RepositoryTest.java, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml
This PR changes the code license from EPL 1.0 to EPL 2.0 and adds a Contribute.md file.
see https://github.com/eclipse/xtext/issues/1176
=> EPL1.0 -> EPL2.0 and contribute.md

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
=> test with MWE 2.11.2.M3

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.22.0

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1682] update orbit to 2020-06
=> [eclipse/xtext#1682] update orbit to 2020-06

releng/org.eclipse.xtext.sdk.p2-repository/pom.xml
maven-antrun-plugin to 3.0.0
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>
=> [https://github.com/eclipse/xtext/issues/1742] Update

releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>
=> [https://github.com/eclipse/xtext/issues/1732] Update to Tycho 1.7.0

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1649] update to ASM 8.0
=> [eclipse/xtext#1649] update to ASM 8.0

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
[eclipse/xtext#1765] update to MWE 2.11.3.M3
=> [eclipse/xtext#1765] update to MWE 2.11.3.M3

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1770] update to mwe 2.11.3 final
=> [eclipse/xtext#1770] update to mwe 2.11.3 final

releng/jenkins/sign-and-deploy/Jenkinsfile
=> increased timeout

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.23.0

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1781] update orbit to 2020-09
=> [eclipse/xtext#1781] update orbit to 2020-09

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0
=> [eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.24.0

releng/jenkins/bot-updates/Jenkinsfile
=> escape $f  in orbit update

releng/jenkins/bot-updates/Jenkinsfile
[eclipse/xtext#1845] fixed orbit update
=> [eclipse/xtext#1845] fixed orbit update

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1828] update orbit to 2020-12
=> [eclipse/xtext#1828] update orbit to 2020-12

Jenkinsfile
[eclipse/xtext-umbrella#223] Fix MissingPropertyException in Jenkinsfile
=> [eclipse/xtext-umbrella#223] Fix MissingPropertyException in Jenkinsfile

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1852] Update to ASM 9
=> [eclipse/xtext#1852] Update to ASM 9

releng/jenkins/bot-updates/Jenkinsfile, releng/jenkins/release-simrel-update/Jenkinsfile, releng/jenkins/sign-and-deploy/Jenkinsfile
[eclipse/xtext#1874] Use human-readable credential IDs
=> [eclipse/xtext#1874] Use human-readable credential IDs

releng/jenkins/release-simrel-update/Jenkinsfile
Makes sure that the build runs with Java 11.
Also introduce a dry-run mode.
=> Simrel update job

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> [releng] Update MWE to 1.6.0/2.12.0

releng/jenkins/sign-and-deploy/Jenkinsfile
=> [eclipse/xtext-umbrella#237] Add Input Step before deleting branches

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.25.0

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1882][2021-03] Update Orbit
DO NOT merge yet
=> [eclipse/xtext#1882][2021-03] Update Orbit

releng/jenkins/release-simrel-update/Jenkinsfile
[eclipse/xtext#1859] Remove deactivation of Parsley for M1
=> [eclipse/xtext#1859] Remove deactivation of Parsley for M1

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
[eclipse/xtext#1925] update to MWE 2.12.1.M2
=> [eclipse/xtext#1925] update to MWE 2.12.1.M2

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1934] update to ASM 9.1
=> [eclipse/xtext#1934] update to ASM 9.1

releng/jenkins/sign-and-deploy/Jenkinsfile
[eclipse/xtext#1954] turn of pack200 by default
=> [eclipse/xtext#1954] turn of pack200 by default

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.26.0

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1944] update orbit to 2021-06
=> [eclipse/xtext#1944] update orbit to 2021-06

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
make guice version more explicit
=> make guice version more explicit

Jenkinsfile, releng/jenkins/release-simrel-update/Jenkinsfile
=> update to maven 3.8.1

releng/jenkins/sign-and-deploy/Jenkinsfile
=> Fix grep args

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> update to orbit 2021-09

releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> add org.aopalliance to xtext update site

releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
add asm.commons to update site
=> add asm.commons to update site

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1981] update to gson 2.8.7
=> [eclipse/xtext#1981] update to gson 2.8.7

Jenkinsfile, releng/jenkins/bot-updates/Jenkinsfile, releng/jenkins/check-versions/Jenkinsfile, releng/jenkins/release-prepare-branches/Jenkinsfile
[eclipse/xtext#1987] Fix agent label deprecation
=> [eclipse/xtext#1987] Fix agent label deprecation

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> use guice 5.0.1

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
=> use MWE2 2.12.2.M1

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1978] update to asm 9.2
=> [eclipse/xtext#1978] update to asm 9.2

Jenkinsfile, releng/jenkins/release-simrel-update/Jenkinsfile
=> update to maven 3.8.2

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties
[eclipse/xtext#2004] update to gradle 7.3
=> [eclipse/xtext#2004] update to gradle 7.3

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2013] update to gson 2.8.8
=> [eclipse/xtext#2013] update to gson 2.8.8

releng/jenkins/check-versions/Jenkinsfile
fix query for xtext-gradle-plugin
=> fix query for xtext-gradle-plugin

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties
=> update to gradle 7.3.1

Jenkinsfile, releng/jenkins/release-simrel-update/Jenkinsfile
=> update to maven 3.8.4

NOTICE.md, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2020] update to classgraph 4.8.138
=> [eclipse/xtext#2020] update to classgraph 4.8.138

releng/docker/xtext-web-deploy/xtext-web/Dockerfile
=> update to jetty 9.4

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties
=> update to gradle 7.3.2

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties
=> update to gradle 7.3.3

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
eclipse/xtext#2025] update to mwe(2) 1.6.2/2.12.2 release
=> eclipse/xtext#2025] update to mwe(2) 1.6.2/2.12.2 release

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2029] update to orbit 2022-03
=> [eclipse/xtext#2029] update to orbit 2022-03

releng/jenkins/bot-updates/Jenkinsfile, releng/jenkins/check-versions/Jenkinsfile, releng/jenkins/release-prepare-branches/Jenkinsfile, releng/jenkins/sign-and-deploy/Jenkinsfile
=> let curl print errors

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2031] update to GSON 2.8.9
=> [eclipse/xtext#2031] update to GSON 2.8.9

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
Do not hard include log4j into Xtext-Features
Fixes #291
=> Do not hard include log4j into Xtext-Features

releng/org.eclipse.xtend.sdk.feature/feature.xml
=> fix log4j dependency

releng/docker/buildenv/Dockerfile
[eclipse/xtext#2036] add jq to xtext-buildenv
=> [eclipse/xtext#2036] add jq to xtext-buildenv

releng/jenkins/bot-updates/Jenkinsfile, releng/jenkins/check-versions/Jenkinsfile, releng/jenkins/release-prepare-branches/Jenkinsfile, releng/jenkins/sign-and-deploy/Jenkinsfile
experiment with using github api to determine xtext version
Fixes https://github.com/eclipse/xtext/issues/2036
=> experiment with using github api to determine xtext version

releng/jenkins/check-versions/Jenkinsfile
=> fix check versions

releng/jenkins/bot-updates/Jenkinsfile
[eclipse/xtext#1973] fix Warning about insecure way to pass secrets in bot-updates job
=> [eclipse/xtext#1973] fix Warning about insecure way to pass secrets in bot-updates job

releng/jenkins/release-prepare-branches/Jenkinsfile
=> better error message

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.27.0

releng/org.eclipse.xtext.generator.feature/.project, releng/org.eclipse.xtext.generator.feature/.settings/org.eclipse.core.resources.prefs, releng/org.eclipse.xtext.generator.feature/.settings/org.eclipse.core.runtime.prefs, releng/org.eclipse.xtext.generator.feature/build.properties, releng/org.eclipse.xtext.generator.feature/feature.properties, releng/org.eclipse.xtext.generator.feature/feature.xml, releng/org.eclipse.xtext.generator.feature/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/pom.xml
[eclipse/xtext#2042] package old generator separately
=> [eclipse/xtext#2042] package old generator separately

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties
=> update to gradle 7.4.1

releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
move xtext.xtext.generator&wizard to xtext.xtext.ui feature
=> move xtext.xtext.generator&wizard to xtext.xtext.ui feature

Jenkinsfile, releng/jenkins/release-simrel-update/Jenkinsfile
=> update to maven 3.8.5

releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/feature.xml
drop packaging of commons.lang
=> drop packaging of commons.lang

releng/org.eclipse.xtext.sdk.p2-repository/pom.xml
bump maven-clean-plugin from 3.0.0 to 3.2.0
=> bump maven-clean-plugin from 3.0.0 to 3.2.0

releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.generator.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2028] switch to reload4j
=> [eclipse/xtext#2028] switch to reload4j

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties
[eclipse/xtext#2051] update to gradle 7.4.2
=> [eclipse/xtext#2051] update to gradle 7.4.2

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
[eclipse/xtext#2054] bootstrap against mwe 2.13.0.M1
=> [eclipse/xtext#2054] bootstrap against mwe 2.13.0.M1

releng/jenkins/bot-updates/Jenkinsfile
=> fix git diff problem

Jenkinsfile, releng/jenkins/bot-updates/Jenkinsfile, releng/jenkins/check-versions/Jenkinsfile, releng/jenkins/release-prepare-branches/Jenkinsfile
[eclipse/xtext#2057] update to centos-8 agent
=> [eclipse/xtext#2057] update to centos-8 agent

releng/org.eclipse.xtext.sdk.p2-repository/pom.xml
=> bumped maven antrun plugin

releng/org.eclipse.xtext.xtext.ui.graph.feature/.settings/org.eclipse.core.resources.prefs
added missing org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs
=> added missing org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs

NOTICE.md, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06
=> [eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2055]simplify dependencies to asm
=> [eclipse/xtext#2055]simplify dependencies to asm

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
=> update to MWE 2.13.0.M2

releng/jenkins/sign-and-deploy/Jenkinsfile
[eclipse/xtext#1987] move sign-and-deploy away from static pod template
=> [eclipse/xtext#1987] move sign-and-deploy away from static pod template

releng/jenkins/cleanup-project-storage/Jenkinsfile
move cleanup-project-storage away from static pod template
See eclipse/xtext#1987
=> move cleanup-project-storage away from static pod template

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2061] Bootstrap against MWE 2.13.0 release
=> [eclipse/xtext#2061] Bootstrap against MWE 2.13.0 release

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.generator.feature/feature.xml, releng/org.eclipse.xtext.generator.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.28.0

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse-pde/eclipse.pde#102] drop removed api.tools.ee.feature
=> [eclipse-pde/eclipse.pde#102] drop removed api.tools.ee.feature

releng/jenkins/sign-and-deploy/Jenkinsfile
Upgrade to Centos 8
Adapt to new version of publishing plugin
Use GPG Credentials
=> Kt issue2065 sign and deploy

NOTICE.md, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2071] update to orbit 2022-09
=> [eclipse/xtext#2071] update to orbit 2022-09

Jenkinsfile, releng/jenkins/release-simrel-update/Jenkinsfile
=> update to maven 3.8.6

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2081] update to gson 2.9.0
=> [eclipse/xtext#2081] update to gson 2.9.0

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.generator.feature/feature.xml, releng/org.eclipse.xtext.generator.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.29.0

NOTICE.md, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson
=> [eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

Jenkinsfile, releng/org.eclipse.xtext.releng.simrel.tests/.classpath, releng/org.eclipse.xtext.releng.simrel.tests/.settings/org.eclipse.jdt.core.prefs, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1982] support for java 17
=> [eclipse/xtext#1982] support for java 17

NOTICE.md, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2104] update to asm 9.4
=> [eclipse/xtext#2104] update to asm 9.4

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
[eclipse/xtext#2106] Update to MWE 2.14.0.M1
=> [eclipse/xtext#2106] Update to MWE 2.14.0.M1

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
use fixed asm 9.4 version from orbit m3
=> use fixed asm 9.4 version from orbit m3

releng/gradle-composite/.settings/org.eclipse.buildship.core.prefs
adapted prefs for latest buildship
=> adapted prefs for latest buildship

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[#196] use 0.0.0 as junit version
=> [#196] use 0.0.0 as junit version

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2112] Fix Orbit signing problem
=> [eclipse/xtext#2112] Fix Orbit signing problem

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2112] switch back to orbit 2022-12
=> [eclipse/xtext#2112] switch back to orbit 2022-12

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.generator.feature/feature.xml, releng/org.eclipse.xtext.generator.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.30.0

adjustPipelines.sh
also adjust pipeline in tycho poms
=> also adjust pipeline in tycho poms

releng/gradle-composite/.settings/org.eclipse.buildship.core.prefs, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2127] Update to EMF 2022-03 (2.29.0)
=> [eclipse/xtext#2127] Update to EMF 2022-03 (2.29.0)

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.generator.feature/feature.xml, releng/org.eclipse.xtext.generator.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.28.1

releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2118] update to orbit 2023-03
=> [eclipse/xtext#2118] update to orbit 2023-03

releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.generator.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml
[eclipse/xtext#2126] bump reload4j
=> [eclipse/xtext#2126] bump reload4j

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2131] update to gson 2.10
=> [eclipse/xtext#2131] update to gson 2.10

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#2131] update to GSON 2.10.1
=> [eclipse/xtext#2131] update to GSON 2.10.1 

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties
[eclipse/xtext#2138] update to gradle 7.6.1
=> [eclipse/xtext#2138] update to gradle 7.6.1

releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtend.sdk.feature/pom.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/pom.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/pom.xml, releng/org.eclipse.xtext.generator.feature/feature.xml, releng/org.eclipse.xtext.generator.feature/pom.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/pom.xml, releng/org.eclipse.xtext.releng.simrel.tests/META-INF/MANIFEST.MF, releng/org.eclipse.xtext.releng.simrel.tests/pom.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/pom.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.p2-repository/pom.xml, releng/org.eclipse.xtext.sdk.parent/pom.xml, releng/org.eclipse.xtext.sdk.target/pom.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/pom.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.graph.feature/pom.xml, releng/pom.xml
=> [releng] Update Xtext version to 2.31.0
