releng/gradle-composite/build.gradle, releng/gradle-composite/gradle.properties, releng/gradle-composite/settings.gradle
Use Whitelist to determine the valid xtext gradle projects. fixes #6
=> Use Whitelist to determine the valid xtext gradle projects. fixes #6

releng/gradle-composite/build.gradle, releng/gradle-composite/settings.gradle
In my old workspace which was not set up with Oomph the repositories have a suffix `.git` in the directory name. The script was not able to generate the preference files for projects in there since the condition did not match.
The change will now test if the directory name contains one of the known project names, e.g. `xtext-core.git` contains `xtext-core`.
=> Fix issue when git directories contain '.git' suffix

releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml
Since xtend.sdk is included in xtext.sdk and since xtend.sdk could be
installed without xtext.sdk (as reported in the bug) I moved the testing
bundles into xtend.sdk
Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=511922
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>
=> 511922: moved testing bundles from xtext.sdk to xtend.sdk

releng/gradle-composite/build.gradle
Avoids invalid path on Windows
=> [#30] Replace backslash in path to rootDir by slash

releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
We once added LSP4J to the Xtext update site in order to not break clients who use Xtext in a Tycho build: `org.eclipse.xtext.ide` has an optional dependency on `org.eclipse.lsp4j`, and Tycho tries to resolve it in any case. Now the situation is different since both Xtext and LSP4J will be part of the Oxygen aggregated update site. Clients can fetch LSP4J either from there or from the [release update site](http://download.eclipse.org/lsp4j/updates/releases/).
=> Removed LSP4J from Xtext update site

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.ui.feature/feature.xml
migrated codetemplates to new wf. https://github.com/eclipse/xtext-eclipse/issues/355
=> migrated codetemplates to new wf. 

releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.docs.feature/feature.xml, releng/org.eclipse.xtext.examples.feature/feature.xml, releng/org.eclipse.xtext.license.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.ui.feature/feature.xml, releng/org.eclipse.xtext.xbase.feature/feature.xml, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
For feature.xml's I assume that they should be updated to the current (release) year, not the change date of change of the file itself.
=> [eclipse/xtext#1160] Update copyright date range

adjustPipelines.sh
[eclipse/xtext#1214] fixed adjustBuildPipelines to adjust maven integ tests too
depends on https://github.com/eclipse/xtext-maven/pull/28
=> [eclipse/xtext#1214] fixed adjustBuildPipelines to adjust maven integ tests too

Jenkinsfile, adjustPipelines.sh
jenkinsPipelineRepo() function has been extended by branch parameter. sed command only replaces the branch name passed to the function.
Replace branch_url_segment property value instead of whole URL.
This change requires changes for eclipse/xtext#1224 in the other repositories.
=> [eclipse/xtext#1224] Changed replaced content

adjustPipelines.sh
With the upstream branch auto-detection it is not needed anymore to modify upstream-repositories.gradle files.
=> [eclipse/xtext#1222] Remove updating of upstream-repositories.gradle 

adjustPipelines.sh
Consider also pom.xml files in /releng folder
Renamed pom property ‚branch_url_segment‘ to ‚upstreamBranch‘ to align it with upstream-repositories.gradle
=> [eclipse/xtext-umbrella#65] Adjust upstream branch

releng/org.eclipse.xtext.releng.simrel.tests/src/org/eclipse/xtext/releng/simrel/tests/RepositoryTest.java
[eclipse/xtext-eclipse#625] removed pack200 test (deprecated)
=> [eclipse/xtext-eclipse#625] removed pack200 test (deprecated)

fixVersions.sh
@kthoms @cdietrich  
Hi 
Here is the improved version of "fixVersionsScript.sh" .
could you please review this pull request. and let me know if some changes required.
Regards,
Prajwal
=> improved version of "fixVersions.sh"

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
Orbit will contain only a single supported version. The fixed version
let the build fail with the upgrade from 5.3.1 to 5.4.0 in Orbit.
=> [#104] Remove version qualifier for JUnit 4 & 5 libraries

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext-core#1077] update to gson 2.8.2
=> [eclipse/xtext-core#1077] update to gson 2.8.2

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1412] use orbit for 2019-06
=> [eclipse/xtext#1412] use orbit for 2019-06

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
Use https://ci.eclipse.org/xtext as default Jenkins URL
=> [eclipse/xtext#1424] Change default Jenkins

releng/docker/buildenv/Dockerfile
JAVA_HOME must point to the JDK home
=> [eclipse/xtext#1418] Set JAVA_HOME env variable

CBI.Jenkinsfile
[eclipse/xtext#1467] Add JIRO as known environment qualifier for build
notification message
=> [eclipse/xtext#1467] Add JIRO as known environment qualifier for build notification message

CBI.Jenkinsfile
The config file id for settings.xml was invalid. Since the settings.xml
is already provided by volume mount in the pod configuration, additional
provisioning was obsolete anyway.
=> [#138] Removed duplicate settings.xml provisioning

releng/gradle-composite/gradle/wrapper/gradle-wrapper.properties, releng/gradle-composite/gradlew, releng/gradle-composite/gradlew.bat
[eclipse/xtext#1489] update to gradle wrapper 5.5
=> [eclipse/xtext#1489] update to gradle wrapper 5.5

releng/jenkins/sign-and-deploy/Jenkinsfile
This pipeline replaces the xtext-snapshots and common-deploy jobs from
JIPP. It signs Xtext artifacts with the Eclipse Signing Service and with
gpg for deployment for OSSRH.
Artifacts are uploaded to OSSRH.
The resulting p2 repository is zipped and uploaded to Eclipse projects
storage and unpacked to the Xtext update locations.
=> [eclipse/xtext#1471] Add sign-and-deploy Jenkinsfile

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1279] use orbit simrel alias directly
=> [eclipse/xtext#1279] use orbit simrel alias directly

releng/org.eclipse.xtext.sdk.feature/feature.xml
- Use xtext32.png instead of modeling32.png for the feature image.
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>
=> [https://github.com/eclipse/xtext/issues/1486]

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1538] use orbit 2019-12
=> [eclipse/xtext#1538] use orbit 2019-12

releng/jenkins/set-version/Jenkinsfile, releng/jenkins/set-version/fixVersions.sh
This job checks out all repositories and creates a target branch on them
to apply version changes. The job can update the Xtext version to
manifests and POMs, and it can set the Xtext bootstrap version. Which
update is performed depends on the given parameters. The job will
usually perform only one update.
The changes are pushed and a pull request is opened for the changes.
=> [releng] Add job for updating versions

releng/jenkins/release-simrel-update/Jenkinsfile
sed command failed since passed in args contained newlines
Failure see https://ci.eclipse.org/xtext/job/releng/job/release-simrel-update/8/
Fixed with replay see https://ci.eclipse.org/xtext/job/releng/job/release-simrel-update/9/
=> [releng] Trim parameters

releng/jenkins/sign-and-deploy/Jenkinsfile
The result from the invocation of get_property.sh needs to be trimmed,
as it contains a trailing newline. This made the build fail while trying
to trigger the version update.
=> [eclipse/xtext#1618] Trim trailing whitespace from shell call result

releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.ui.feature/feature.xml
The functionality of both plugins does make sense in the context of arbitrary Xtext languages and should be available by default. It does not make much sense to have these only as part of the SDK.
=> Add xtext.m2e and xtext.buildship to features xtext.redist and xtext.ui

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1673] udpate to MWE 2.11.2
=> [eclipse/xtext#1673] udpate to MWE 2.11.2

releng/jenkins/release-simrel-update/Jenkinsfile
I have configured the job https://ci.eclipse.org/xtext/job/releng/job/release-simrel-update-issue1814/ to use the branch.
It is failing ATM, but later and for different reason. I assume the basic Git problem is solved with the change.
=> [eclipse/xtext#1814] Use 'basic' pod template for simrel job

Jenkinsfile, releng/jenkins/release-simrel-update/Jenkinsfile
The centos-7 pod template provides a configuration suitable for most
builds. This makes the configuration of the custom container obsolete.
Additionally JDK versions are now selectable by parameter.
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
=> [eclipse/xtext#1812] Use centos-7 pod template & config. JDK

releng/jenkins/bot-updates/Jenkinsfile
This change extends the 'Update Orbit URL' stage to update the Orbit URL
in TargetPlatformProject.xtend|java.
Additionally some enhancements have been made to the pipeline:
- The steps to commit changes have been moved to a new function
'commitChanges()'. All modification stages call the function at their
end. The function prints out the committed changes when the DRY_RUN flag
has been set.
- An unnecessary 'script' block has been removed when setting
currentBuild.displayName. The actions are already performed within a
script block.
- Copy/paste errors in the comments on the closing braces for stages
have been fixed.
The resulting changes for an Orbit URL update can be seen here: https://ci.eclipse.org/xtext/job/releng/job/bot-updates/83/console
The build was run as DRY_RUN, so it prints …
=> [eclipse/xtext#1846] Update Orbit URLs in wizard

releng/jenkins/sign-and-deploy/Jenkinsfile
[eclipse/xtext#1502] Remove old milestones when deploying new M1
=> [eclipse/xtext#1502] Remove old milestones when deploying new M1

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.feature/feature.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target, releng/org.eclipse.xtext.xtext.ui.feature/feature.xml
[eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2
=> [eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2

releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
Following platform upgrade of GSON from Bug#569966.
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
=> [eclipse/xtext#1916] Upgrade GSON to 2.8.6

releng/org.eclipse.xtend.sdk.feature/feature.xml, releng/org.eclipse.xtext.redist.feature/feature.xml, releng/org.eclipse.xtext.runtime.feature/feature.xml, releng/org.eclipse.xtext.sdk.p2-repository/category.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
Update Google Guava version from 27.1.0 to 30.1.0
Signed-off-by: miklossy <miklossy@itemis.de>
=> https://github.com/eclipse/xtext/issues/1862 Guava 30.1.0

releng/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml, releng/org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml, releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target
[eclipse/xtext#1928] Bootstrap against MWE(2) 1.6.1/2.12.1 Final
=> [eclipse/xtext#1928] Bootstrap against MWE(2) 1.6.1/2.12.1 Final

releng/org.eclipse.xtext.sdk.p2-repository/pom.xml
The version qualifier of the target zip file uses an introduced
property. This allows easier sed commands to replace the value.
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
=> [eclipse/xtext#1875] Introduce property for zip file version

releng/jenkins/bot-updates/Jenkinsfile
With installation of the build-user-vars-plugin we can now access the
name and email of the current user requesting the job execution. This
can be used to configure the git repos for this user and have proper
sign offs.
I have used this plugin already here:
https://github.com/eclipse/xtext-umbrella/blob/kt_xtext1875_jenkinsfiles_to_umbrella/releng/jenkins/release-prepare-branches/Jenkinsfile
https://ci.eclipse.org/xtext/job/experimental/job/release-prepare-branches-issue1875/73/console
Here is a sample commit with the proper sign off:
https://github.com/eclipse/xtext-lib/commit/5a0de54c1b115583e0a6ca20eb0ca2ad5543475c
=> Use BuildUser to configure git user name / email

releng/jenkins/release-prepare-branches/Jenkinsfile
This adds the 'release-prepare-branches' job which was hosted in repository xtext-build-tools so far.
This version enhances the original one:
- No external Groovy scripts are used, instead inlined ones and usage of sed commands for text replacements
- Using default agent 'centos-7'
- More logging
- For committing the current user is configured, i.e. commits are not issued by the bot user
- Reduced complexity
For testing the job https://ci.eclipse.org/xtext/job/experimental/job/release-prepare-branches-issue1875 uses this Jenkinsfile. The latest builds show the execution with DRY RUN.
With Dry Run the resulting diffs are printed. Compare the changes to those that have been done with the old job (using the tagged commit for release 2.25.0):
- xtext-lib: …
=> [eclipse/xtext#1875] Add 'release-prepare-branches' job

releng/jenkins/check-versions/Jenkinsfile
This moves the check-versions job to xtext-umbrella. The groovy functions from 'version_functions.groovy' have been inlined here.
Here is the executed job for this branch:
https://ci.eclipse.org/xtext/job/experimental/job/check-versions-issue1522/5/
=> Move check_versions from xtext-build-tools

Jenkinsfile, releng/jenkins/release-simrel-update/Jenkinsfile
[eclipse/xtext#1995] switch from adoptopenjdk to termurin and provide java 17 jdk
=> [eclipse/xtext#1995] switch from adoptopenjdk to termurin and provide java 17 jdk

releng/jenkins/release-prepare-branches/Jenkinsfile
support RC1 and RC2 in release-prepare-branches.
Fixes eclipse/xtext#2037
=> support RC1 and RC2 in release-prepare-branches.

releng/gradle-composite/GenerateBuildshipPreferences.launch
[eclipse/xtext#2110] dont run GenerateBuildshipPreferences.launch in background
=> [eclipse/xtext#2110] dont run GenerateBuildshipPreferences.launch in background 
